---
- name: "Inicializar estado por host"
  set_fact:
    file_status: "UNREACHABLE"

- block:

    - name: "Ensure destination directory exists"
      ansible.builtin.file:
        path: "{{ remote_dest_dir }}"
        state: directory
        mode: '0755'

    - name: "Copy Commvault script to host"
      ansible.builtin.copy:
        src: "{{ local_tmp_dir }}/{{ file_name }}"
        dest: "{{ remote_dest_dir }}/{{ file_name }}"
        mode: '0755'

    - name: "Marcar distribución exitosa"
      set_fact:
        file_status: "EXISTE"

  rescue:
    - name: "Marcar fallo de distribución"
      set_fact:
        file_status: "ERROR_DISTRIBUCION"

  ignore_errors: true
