---
- name: "Ensure temp directory exists on AAP"
  ansible.builtin.file:
    path: "{{ local_tmp_dir }}"
    state: directory
    mode: '0755'
  delegate_to: localhost
  run_once: true

- name: "Download Commvault script from GCP bucket"
  google.cloud.gcp_storage_object:
    action: download
    bucket: "{{ gcp_bucket }}"
    src: "{{ gcp_object }}"
    dest: "{{ local_tmp_dir }}/{{ file_name }}"
    project: "{{ gcp_project }}"
  delegate_to: localhost
  run_once: true
