---
- name: "Commvault | Dynamic inventory"
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - commvault_distribution

- name: "Commvault | Distribución tolerante a fallos"
  hosts: dynamic_temporal_hosts
  gather_facts: false
  strategy: free
  max_fail_percentage: 100
  ignore_unreachable: true

  roles:
    - commvault_distribution
