---
# Proyecto: operating-systems-file-management
# Ubicación: - Proyecto/roles/commvault_prepare/tasks/main.yml

# Crear inventario dinámico
- name: "Create dynamic inventory"
  ansible.builtin.add_host:
    name: "{{ item }}"
    groups: dynamic_temporal_hosts
  loop: "{{ host_to_add }}"

# Preparar directorio temporal
- name: "Ensure temp directory exists"
  ansible.builtin.file:
    path: "/tmp/{{ gcp_subdirectory }}"
    state: directory
    mode: '0755'

- name: "Asegurar que el archivo de reporte CSV existe con encabezados"
  ansible.builtin.copy:
    dest: "/tmp/{{ gcp_subdirectory }}/report.csv"
    content: "IP,Hostname,,Archivo,Estado\n"
    force: true # Esto limpia el reporte viejo en cada ejecución nueva
    mode: '0644'

# Descargar desde GCP
- name: "Download Commvault script from GCP"
  google.cloud.gcp_storage_object:
    action: download
    bucket: "{{ gcp_bucket }}"
    src: "{{ gcp_object }}"
    dest: "/tmp/{{ gcp_subdirectory }}/{{ gcp_archive }}"
    #dest: "/tmp/{{ gcp_object }}/{{ gcp_archive }}"
    project: "{{ gcp_project }}"
